### ISSUE TITLE
Wrongly detecting x264 as H.264

### ISSUE THREAD

**Issue by simbab0i** [L4GSP1KE/Upload-Assistant#17]
I am using the script to upload a TV Series, `VideoCodec` is `x264`.

The folder name:
**Some.Series.S01.1080p.NF.WEB-DL.DDP5.1.x264-GroupName**

from MediaInfo:
```
Video
ID                                       : 1
Format                                   : AVC
```

and [here](https://github.com/L4GSP1KE/Upload-Assistant/blob/5c18162cb3eba2e1e47804fbd840d8de9e08974a/src/prep.py#L1352) it doesn't look very right to me:
```python
elif type == 'WEBDL': #WEB-DL
   if format == 'AVC':
      codec = 'H.264'
   elif format == 'HEVC':
      codec = 'H.265'
```
because `mediainfo`ing the file shows:
```
Format/Url                               : http://developers.videolan.org/x264.html
```

So, there's a probability it could be x264. I don't know based on what because I am not very experienced with `VideoCodecs`, but maybe search for such `Format/Url` and give it a higher priority. `mediainfo --fullscan video.mkv` gives good information.

Also, I'd appreciate an argument when I respond `N (no)` to
```
Name: The Name
:: Correct? (y/N)
```
to be able and set `--audiocodec X` & `--videocodec Y`.

Thank you.

**Comment by L4GSP1KE** [comment]
This is not an error. MPEG-4 AVC, also known as H.264, is the name of the codec. x264 is the popular, free, open source encoding software for AVC/H.264. The standards/naming conventions ended up so that we use AVC for "raw" sources and x264 for encoded releases. This leaves us with the interesting case of WEB-DLs. Since actual WEB-DL's are technically encodes (same with BDs, but streaming services aim for a much higher compression), while also being a 1:1 "raw" from the source. This resulted in a different set of rules depending on which site you'd upload to. Some sites prefer WEB-DL = H.264, some sites prefer H.264 but x264 if the streaming service left in the encoding settings, and some sites don't care. The script edits the title on a site-by-site basis if needed.

`--audiocodec`/`--videocodec` will not happen because if the script manages to incorrectly identify either of those from the mediainfo, I'd much have you submit an issue like you've done here so we can have it work correctly for future releases.
