### ISSUE TITLE
Daily format not always working

### ISSUE THREAD

**Issue by LostRager** [L4GSP1KE/Upload-Assistant#195]
For some reason, the daily format worked from the year 2014.01.01 until 2015.10.14 and then it stopped working for me. 
Could you implement an arg to force daily format?

The titles on all the files are pretty much identically:
Jimmy.Fallon.2015.10.14.Vin.Diesel.720p.HDTV.X264-UAV.mkv (got correct title)
Jimmy.Fallon.2015.10.15.Tom.Hanks.720p.HDTV.X264-UAV.mkv (got incorrect title)

**Comment by mesol86** [comment]
Agreed, somehow GG Bot able to handle daily show. L4G keeps giving regardless of date as S01.

**Comment by L4GSP1KE** [comment]
Looks like it was defaulting to S01 because it was unable to map that episode to the Season/Episode format due to tmdb not having that episode listed (this is only really shown if someone decides to view it with grouping enabled). Shouldn't be an issue anymore. 
Also added `--daily` for any spare cases when it guesses the wrong date.

https://github.com/L4GSP1KE/Upload-Assistant/commit/4347fd58bc3b6522663fc21ecc32110649a932ef https://github.com/L4GSP1KE/Upload-Assistant/commit/b48788ce2640a7c3c203f5fae46642d8cc1342e1

**Comment by LostRager** [comment]
Thank you for the quick fix, It works like a charm <3
