### ISSUE TITLE
Washed out screenshots

### ISSUE THREAD

**Issue by MasalaTalk** [L4GSP1KE/Upload-Assistant#299]
Earlier HDR releases screenshots were correctly showing tonemapped, but now they're just washed out like any other screenshot grabber.
what happened? any changes in the settings?

**Comment by vincejv** [comment]
It depends on the ffmpeg version used, or vapoursynth

**Comment by MasalaTalk** [comment]
> It depends on the ffmpeg version used, or vapoursynth

it's working on and off on it's on without any intervention from my side. on one day it's showing showing correct, other day it's showing washedd out. currently it's all washed out.

**Comment by vincejv** [comment]
> > It depends on the ffmpeg version used, or vapoursynth
> 
> it's working on and off on it's on without any intervention from my side. on one day it's showing showing correct, other day it's showing washedd out. currently it's all washed out.

l4g uploader does not make the screenshots, but uses ffmpeg or vapursynth or generate it, you proabbly upgraded your ffmpeg or vapoursynth to a later version using `apt upgrade` or `yum upgrade` whatever distro you used, use the docker image instead `docker pull ghcr.io/l4gsp1ke/upload-assistant:master` since it uses a fixed version of ffmpeg
