### ISSUE TITLE
adding a new tracker 

### ISSUE THREAD

**Issue by TheScenePlace** [L4GSP1KE/Upload-Assistant#42]
hi there, 

looking to make a switch of torrent tracker software from torrenttrader to unit3d source code, was wondering how i go about getting the site's url added to supported list for the bot?

**Comment by L4GSP1KE** [comment]
1. Fork and edit the [UNIT3D Template](https://github.com/L4GSP1KE/Upload-Assistant/blob/master/src/trackers/UNIT3D_TEMPLATE.py) for your site. 
2. Make sure it works how you want it
3. Submit a PR or get back to me with your tracker file and we can get it added in for ya

I just added in STT which you can use as a reference if needed, although I think they used an existing tracker file instead of the template (https://github.com/L4GSP1KE/Upload-Assistant/commit/8a6407fa74f6bcf660e945c88b4af69b46697a10)

Feel free to reach out with any questions

**Comment by swannie-eire** [comment]
@TheScenePlace I assume with the name you are talking about thesceneplace tracker?

thesceneplace does not currently use UNIT3D but if it does in the future i can write the code for it.

GG-UPLOAD can upload to that site if you are looking for a script that can.

**Comment by TheScenePlace** [comment]
No sorry, this account was made back when I owned thesceneplace, now I own https://hidden-palace.net/

**Comment by swannie-eire** [comment]
> No sorry, this account was made back when I owned thesceneplace, now I own https://hidden-palace.net/

Ah ok, I dont have an account there so cant help.

**Comment by TheScenePlace** [comment]
registrations are open, your welcome to come and join :)

**Comment by swannie-eire** [comment]
> registrations are open, your welcome to come and join :)

from the looks of it you or someone else have already done it since i just checked the source of an existing torrent and found.
![Screenshot 2022-03-23 at 10 17 08](https://user-images.githubusercontent.com/57441681/159676843-703162bf-caf9-4e32-ab9d-aa07f6b1871e.png)

**Comment by TheScenePlace** [comment]
yeah think my mate sorted one but didnt know till about half hr ago

**Comment by swannie-eire** [comment]
lovely have them add it here so everyone can be singing off the same page.

**Comment by FuNFooKaS** [comment]
pmed you on discord

**Comment by TheScenePlace** [comment]
hey guys, instead of making a new issue thought i'd reply to this one... bot is running nicely, but we're noticing when we download any of megusta rls groups torrents, the bot isnt name the torrent correctly cause they're not releasing the torrent with the file type e.g web-dl or web-rip or that.. any ideas?

**Comment by L4GSP1KE** [comment]
the solution is to pass something like `--type webrip`
