### ISSUE TITLE
Screenshots too large, HDR screenshots washed out

### ISSUE THREAD

**Issue by cyboris7** [L4GSP1KE/Upload-Assistant#59]
I mainly use this script for 4k bluray remux content. Screenshots are regularly >32mb and it can take literally ~100 attempts per screenshot to take one that fits onto Imgbb with the message "Image too large for your image host, retaking".

I tried playing with "optimize_images" true/false, but could not notice any difference. Am I using that configuration incorrectly? Is there some other functionality that can transparently (not visible to humans) compress the image to save hours of time retaking screenshots?

When taking images of a HDR video the resulting screenshot are very washed out, ive shown a ffmpeg screenshot verses VLC playing on an SDR monitor). I believe this is an ffmpeg issue, as there are several posts around about remapping the color:
https://www.reddit.com/r/ffmpeg/comments/i2nm7n/capture_screenshot_from_hevc_10_bit_look_very_pale/
https://www.reddit.com/r/ffmpeg/comments/8zmbn4/have_any_tips_for_reencoding_4k_content/

Im not actually sure if this is even fixable within this script, but thought i would bring it up as worth investigating.

Otherwise this program works completely flawlessly for me everyday, thank-you for your great work!

![image](https://user-images.githubusercontent.com/108043497/175205326-2af6abda-7320-4499-8507-b7701447ea9d.png)

**Comment by L4GSP1KE** [comment]
I've made some tweaks so that image compression will be more aggressive with larger screenshots when enabled (this will take longer though). The best solution is to use an image host with a larger size limit (getting a ptpimg account isn't too hard). If you know of any _good_ image hosts that you'd like to see supported please let me know. 

RE: Tonemapping. Yes it's possible but i'd rather have people complain about non-tonemapped screens than thinking the hdr grade is bad due to a bad tonemap
