### ISSUE TITLE
local variable 'web_url' referenced before assignment

### ISSUE THREAD

**Issue by waldens** [L4GSP1KE/Upload-Assistant#6]
Win7 x64 + Python 3.8.6 x64

![snipaste20210731_153039](https://user-images.githubusercontent.com/3130930/127732548-78e5d3c8-c3b3-4c03-8190-885c8893b5cb.png)

```
{
    "DEFAULT" : {
        "tmdb_api" : "1cc2b22b8440f6e33e9c70d47c41a3f1",

        "imgbb_api" : "imgbb api key",
        "pstorage_api" : "pstorage.space api key",
        "freeimage_api" : "6d207ea0198a847aa98e0a2a901485a5",
        "ptpimg_api" : "a92aeea5-a58a-4937-aef3-02c98e03306d",

        "img_host_1": "imgbb",
        "img_host_2": "freeimage.host",
        "img_host_3": "ptpimg",
        "img_host_4": "pstorage",
        "img_host_5": "imgbox",

        "anon" : "False",
        "screens" : "6",



        "default_torrent_client" : "Client1"
......
```
No worry, API Key above are placeholder just for show.

**Comment by L4GSP1KE** [comment]
This issue has been fixed. Thanks for bringing it to my attention. I recommend setting the img_host order to the order you wish to use, for example if you want to use mainly use pstorage and have freeimage as a backup set img_host_1 to pstorage and img_host_2 to freeimage.host. Also this script will not work with DVDRips due to them generally being banned and low quality
